// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.CatanAssignment1;

/************************************************************/
/**
 * 
 */
public enum ResourceType {
	/**
	 * 
	 */
	WOOD,
	/**
	 * 
	 */
	BRICK,
	/**
	 * 
	 */
	WHEAT,
	/**
	 * 
	 */
	SHEEP,
	/**
	 * 
	 */
	ORE,
	/**
	 * 
	 */
	DESERT;
}
