// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package main.CatanAssignment1;

/************************************************************/
/**
 * 
 */
public enum StructureType {
	/**
	 * 
	 */
	NONE,
	/**
	 * 
	 */
	SETTLEMENT,
	/**
	 * 
	 */
	CITY;
}
