// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class Board {
	/**
	 * 
	 */
	public void setupMap() {
	}

	/**
	 * 
	 * @param roll 
	 */
	public void produce(int roll) {
	}

	/**
	 * 
	 * @return 
	 * @param p 
	 * @param action 
	 */
	public boolean validateBuild(Player p, BuildAction action) {
	}

	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public Edge getIncidentEdges(Node n) {
	}

	/**
	 * 
	 * @param n 
	 * @return 
	 */
	public Node getNeighbourNodes(Node n) {
	}
}
