// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class BuildAction {
	/**
	 * 
	 */
	private BuildType type;
	/**
	 * 
	 */
	private Node node;
	/**
	 * 
	 */
	private Edge edge;

	/**
	 * 
	 * @return 
	 */
	public String describe() {
	}

	/**
	 * 
	 * @return 
	 */
	public ResourceMap cost() {
	}
}
