// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class Edge {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Player roadOwner;
}
