// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class Node {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private Player structureOwner;
	/**
	 * 
	 */
	private StructureType structureType;
}
