// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class Player {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private int victoryPoints;

	/**
	 * 
	 * @return 
	 */
	public int rollDice() {
	}

	/**
	 * 
	 * @param board 
	 */
	public void takeTurn(Board board) {
	}
}
