// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class ResourceHand {
	/**
	 * 
	 */
	private ResourceMap resources;

	/**
	 * 
	 * @return 
	 */
	public int totalCards() {
	}
}
