// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class Simulator {
	/**
	 * 
	 */
	private int maxRounds;
	/**
	 * 
	 */
	private int currentRound;

	/**
	 * 
	 */
	public void runSimulation() {
	}

	/**
	 * 
	 * @return 
	 */
	public boolean checkWin() {
	}
}
