// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package CatanAssignment1;

/************************************************************/
/**
 * 
 */
public class Tile {
	/**
	 * 
	 */
	private int id;
	/**
	 * 
	 */
	private ResourceType resourceType;
	/**
	 * 
	 */
	private int numberToken;

	/**
	 * 
	 */
	public void produce() {
	}
}
